//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C90dScrapTotals
    {
        public string ID { get; set; }
        public string Product { get; set; }
        public Nullable<double> Scrapped { get; set; }
        public string Reason { get; set; }
        public string Line { get; set; }
        public Nullable<decimal> Produced { get; set; }
    }
}
